### ISSUE TITLE
Viewer visual bug

### ISSUE THREAD

**Issue by sergio-aguiar** [dgomes/iia-ia-bomberman#11]
Dying on the same spot where you placed a bomb makes the bomb sprite remain on that spot (without the animation) until either a new bomb is placed on that exact same spot or the level is beaten. Any actual bombs placed will meanwhile not show up on the viewer and walls that get destroyed will not disappear until the bomberman walks over them.

**Comment by sergio-aguiar** [comment]
Actually, it seems like it's due to being killed by an enemy while a bomb is active.

**Comment by dgomes** [comment]
pretty sure I corrected this in the last commits

**Comment by dgomes** [comment]
https://github.com/dgomes/iia-ia-bomberman/commit/eb87a04187ebaee64cb0777bb3a6f658149cd643
