### ISSUE TITLE
conversão tuplo/lista

### ISSUE THREAD

**Issue by pedralmeida22** [dgomes/iia-ia-bomberman#8]
![Screenshot from 2019-10-24 10-56-37](https://user-images.githubusercontent.com/40249872/67474964-38f4e900-f64d-11e9-9fe8-ef9291308396.png)
![Screenshot from 2019-10-24 10-56-47](https://user-images.githubusercontent.com/40249872/67474984-401bf700-f64d-11e9-95a5-1294b190139e.png)

Função is_blocked funciona mal devido a isso.

**Comment by dgomes** [comment]
isto acontece pq estão a usar método `is_blocked` do `Map` depois de martelarem as walls do `state` que recebe (que vem em list e não tuplos)

Acrescentei um setter novo em `Map` em 55486c30d36e8ed5399254f04e301e433899ede7, agora podem fazer:

`
mapa.walls = state['walls']
`

Desta forma este problema não existe.
